# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ssd_pytorch',
                'doc_host': 'https://thatgeeman.github.io',
                'git_url': 'https://github.com/thatgeeman/ssd_pytorch',
                'lib_path': 'ssd_pytorch'},
  'syms': {'ssd_pytorch.core': {'ssd_pytorch.core.foo': ('core.html#foo', 'ssd_pytorch/core.py')}}}
